### ISSUE TITLE
Application crashes with exception

### ISSUE THREAD

**Issue by vjalle** [gsp-p-77/vxlapiCanTrace#1]
Built the app as described, using the MSYS2 UCRT64 compiler. It crashes with a "cygwin exception" when calling xlOpenPort().
Got the same result with the MSYS2 MingW64 and the Cygwin Mingw64 compilers.
Maybe it only works with MS compilers?

g++ -DWIN64 -m64 -g vxlapiCanTrace.cpp -L. -l:vxlapi64.lib

Edit: does not crash with MSVC. Could not get any frames sent to the Virtual CAN with CANOe though...

**Comment by gsp-p-77** [comment]
Hello vjalle, thank you for your issue report.

Your assumption is right. The build depends on MSVC (https://code.visualstudio.com/docs/cpp/config-msvc) due to the dependency constraints of the vxlapi library (ref. to https://www.vector.com/gb/en/products/products-a-z/libraries-drivers/xl-driver-library/#c75541)

I just tried again to build the executable and can confirm your issue.

I will add this to the README.MD file, to make this clear.

BR
Geri

**Comment by gsp-p-77** [comment]
Clarified with update of README.md: https://github.com/gsp-p-77/vxlapiCanTrace/commit/19967f0557cf820f6f94315794d7b9a00ea83da1

**Comment by vjalle** [comment]
Thanks!

**Comment by vjalle** [comment]
Ehh... My mistake. The VS Code debugger was one line off for some reason. The crash is happening in the printf() statements following the XL lib calls. It seems that "%I64x" is MSVC-specific and crashes GCC. If you replace them with "%llx" or similar (or comment out the offending lines entirely), there is no crash anymore, the app starts normally. Communication through the library I could not test yet.

**Comment by vjalle** [comment]
Confirmed, after fixing the printf() format strings, the app is working with GCC too (tested with the UCRT64 environment in MSYS2). It's sending and receiving frames through the library properly.
Maybe it's worth fixing in your code too, to make it more universal.

**Comment by gsp-p-77** [comment]
Thank you, for the update. Sounds very good. Can you provide a pull request?
